### PR TITLE
Use filter codes instead of filter names (from shamanskyh 🙂)

### PR DESCRIPTION
**Pull request by nathanfjohnson**
Just taking this PR made by @shamanskyh https://github.com/aschzero/homebridge-airmega/pull/12

### CODE REVIEW

**Comment by GTPatriots** [comment]
@nathanfjohnson , now that you've forked this project and merged this fix how would 1 install your version in homebridge?

**Comment by nathanfjohnson** [comment]
> @nathanfjohnson , now that you've forked this project and merged this fix how would 1 install your version in homebridge?

Not exactly sure, I haven’t used typescript or npm before. I’ll post here when I figure it out. Or you can give it a go.

**Comment by nathanfjohnson** [comment]
We'll need to figure out how to replace "request", I'm thinking of axios, though I'm not a typescript engineer. https://github.com/request/request/issues/3143

**Comment by GTPatriots** [comment]
May I suggest updating the landing page since the current instructions would install the original from @aschzero.  At least until it's figured out.  Highly unlikely I can help.  Never worked with TS, JS, or NPM before.  Very new to homebridge.

**Comment by nathanfjohnson** [comment]
Yes, well it's not working at the moment, if I get it working I will update it all.

**Comment by GTPatriots** [comment]
That's kinda my point.  Suggest updating the landing page readme file to say this is a work in progress and not have instructions that tell you how to install @aschzero's broken version.

**Comment by nathanfjohnson** [comment]
I see what you mean, would you also recommend the same to the other 5 forks of this repo? I don’t think that’s necessary right now since I haven’t published this fork to npm with the appropriate tags for it to be searchable.

**Comment by GTPatriots** [comment]
Gotcha, maybe just jumping the gun.  As I said new to this stuff.  Eager to have this filter bug fixed that you merged in and hopeful that you or someone else will be willing to look at the other issue I found where the logic to send commands seems to be off as well.  Appreciate you taking the 1st step!

**Comment by nathanfjohnson** [comment]
Ok, sorry @GTPatriots, I have some bad news for you. After trying to update this plugin and replace all the old deprecated frameworks, I ended up starting to just make my own for Home Assistant. Then I found out that it was already done. https://github.com/sarahhenkens/home-assistant-iocare
I've only tested it for a few moments and it's already clear how much better it is than the HomeBridge plugin. I used the Home Assistant Home Kit integration and it's working great in Home Kit now. Fun fact, that was the last of my HomeBridge plugins, so I'm 100% moved to Home Assistant. HomeBridge has been great though, I used it for several years.

**Comment by GTPatriots** [comment]
Thanks for checking @nathanfjohnson.  I'm going to check out Home Assistant.  This was my 1 and only plugin so if it's working well in Home Assistant maybe that's the thing for me.  Looks a little less plug n play, but doable, if you have any advice I'd appreciate it.

**Pull request merged**
